Examen2/ToDoView/Client/urls.py
from django.urls import path
from Client import views

app_name = 'Client'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('id_title/', views.ListToDoIDandTitle.as_view(), name='idtitle'),
    path('id_userid/', views.ListToDoIDandUserID.as_view(), name='iduserid'),
    
    path('unsolved/id_title', views.ListToDoIDandTitleUnsolved.as_view(), name='unsolved_idtitle'),
    path('unsolved/id_userid', views.ListToDoIDandUserIDUnsolved.as_view(), name='unsolved_iduserid'),
    
    path('solved/id_title', views.ListToDoIDandTitleSolved.as_view(), name='solved_idtitle'),
    path('solved/id_userid', views.ListToDoIDandUserIDSolved.as_view(), name='solved_iduserid'),
    
    
    path('create/', views.CreateToDoView.as_view(), name='create'),
    path('update/<int:pk>/', views.UpdateToDoView.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeleteToDoView.as_view(), name='delete'),
    path('detail/<int:pk>/', views.DetailToDoView.as_view(), name='detail'),
    
    
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    
]

Examen2/ToDoView/ToDoView/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Client.urls'))
]

Examen2/ToDoView/Client/models.py
from django.db import models

# Create your models here.

Examen2/ToDoView/Client/forms.py
from django import forms



STATUS_CHOICES = [
    ('pending', 'Pending'),
    ('in_progress', 'In Progress'),
    ('completed', 'Completed'),
]
    
PRIORITY_CHOICES = [
    ('low', 'Low'),
    ('medium', 'Medium'),
    ('high', 'High'),
]


class CreateToDoForm(forms.Form):
    title = forms.CharField(label='Title', max_length=64)
    status = forms.CharField(max_length=16, widget= forms.Select(choices=STATUS_CHOICES , attrs={"type":"select", "class":"form-select form-control"}))
    description = forms.CharField( label='Description', max_length=128, widget=forms.Textarea(attrs={ "class": "form-control", "rows": 4, "placeholder": "Enter task description" }))
    due_date = forms.DateTimeField( label='Due Date', widget=forms.DateTimeInput(attrs={ "type": "datetime-local", "class": "form-control", "placeholder": "Select date and time" }))
    priority = forms.CharField(max_length=16, widget= forms.Select(choices=PRIORITY_CHOICES , attrs={"type":"select", "class":"form-select form-control"}))
    


    

Examen2/ToDoView/Client/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .forms import CreateToDoForm
import requests
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt



#################################################### TO DO ALL ####################################################
class Index(generic.View):
    template_name = 'client/indexid.html'
    url_get = 'http://127.0.0.1:8000/api/todos/ids'
    url_post = 'http://127.0.0.1:8000/api/validate_login/'
    context = {}

    def get(self, request):
        # Verificar si el usuario está autenticado
        if 'username' in request.session and 'validation_number' in request.session:
            self.response = requests.get(url=self.url_get)
            self.context = {"ids": self.response.json()}
            return render(request, self.template_name, self.context)
        else:
            # Si no está autenticado, mostrar el modal de login
            self.context['show_login_modal'] = True
            return render(request, self.template_name, self.context)

    def post(self, request):
        payload = {
            "username": request.POST.get("username"),
            "password": request.POST.get("password"),
        }
        self.response = requests.post(url=self.url_post, data=payload)
        data = self.response.json()

        # Guardar en sesión si el login es exitoso
        if self.response.status_code == 200 and data.get('validation_number'):
            request.session['username'] = data['username']
            request.session['validation_number'] = data['validation_number']
        
        return redirect("Client:index")
    
class ListToDoIDandTitle(generic.View):
    template_name = 'client/indexidtitle.html'
    url_get = 'http://127.0.0.1:8000/api/todos/ids/titles'
    context = {}
    response = None
    def get(self, request):
        self.response = requests.get(url=self.url_get)
        self.context = {
            "idsandtitle":self.response.json()
        }
        return render(request, self.template_name, self.context)
    
class ListToDoIDandUserID(generic.View):
    template_name = 'client/indexiduserid.html'
    url_get = 'http://127.0.0.1:8000/api/todos/ids/userids'
    context = {}
    response = None
    def get(self, request):
        self.response = requests.get(url=self.url_get)
        self.context = {
            "idsanduserid":self.response.json()
        }
        return render(request, self.template_name, self.context)
    
    
#################################################### TO DO UNSOLVED ####################################################
class ListToDoIDandTitleUnsolved(generic.View):
    template_name = 'client/indexidtitle.html'
    url_get = 'http://127.0.0.1:8000/api/todos/unsolved/ids/titles'
    context = {}
    response = None
    def get(self, request):
        self.response = requests.get(url=self.url_get)
        self.context = {
            "idsandtitle":self.response.json()
        }
        return render(request, self.template_name, self.context)


class ListToDoIDandUserIDUnsolved(generic.View):
    template_name = 'client/indexiduserid.html'
    url_get = 'http://127.0.0.1:8000/api/todos/unsolved/ids/userids'
    context = {}
    response = None
    def get(self, request):
        self.response = requests.get(url=self.url_get)
        self.context = {
            "idsanduserid":self.response.json()
        }
        return render(request, self.template_name, self.context)
    
    
#################################################### TO DO SOLVED ####################################################
class ListToDoIDandTitleSolved(generic.View):
    template_name = 'client/indexidtitle.html'
    url_get = 'http://127.0.0.1:8000/api/todos/solved/ids/titles'
    context = {}
    response = None
    def get(self, request):
        self.response = requests.get(url=self.url_get)
        self.context = {
            "idsandtitle":self.response.json()
        }
        return render(request, self.template_name, self.context)
    
    
class ListToDoIDandUserIDSolved(generic.View):
    template_name = 'client/indexiduserid.html'
    url_get = 'http://127.0.0.1:8000/api/todos/solved/ids/userids'
    context = {}
    response = None
    def get(self, request):
        self.response = requests.get(url=self.url_get)
        self.context = {
            "idsanduserid":self.response.json()
        }
        return render(request, self.template_name, self.context)
    
    
#################################################### TO DO CRUD ####################################################
class CreateToDoView(generic.View):
    template_name = 'client/createtodo.html'
    url_post = 'http://127.0.0.1:8000/api/todos/new'
    url_get = 'http://127.0.0.1:8000/api/users'
    context = {}
    form_class = CreateToDoForm
    response = None
    def get(self, request):
        self.response = requests.get(url=self.url_get)
        self.context = {
            "form": self.form_class,
            "idusers":self.response.json()
        }
        return render(request, self.template_name, self.context)
    def post(self, request):
        payload = {
            "title": f"{request.POST.get("title")}",
            "userid": int(request.POST.get("userid")),
            "status": f"{request.POST.get("status")}",
            "description": f"{request.POST.get("description")}",
            "due_date": f"{request.POST.get("due_date")}",
            "priority": f"{request.POST.get("priority")}",
             
            "completed_at": None,
        }
        print(payload)
        self.response = requests.post(url=self.url_post, data=payload)
        return redirect("Client:index")
    
    
class DetailToDoView(generic.View):
    template_name = "client/detailtodo.html"
    context = {}
    url = "http://127.0.0.1:8000/api/todos"
    url2 = "http://127.0.0.1:8000/api/users"
    response = None
    def get(self, request, pk):
        print(pk)
        self.url = self.url + f'/{pk}'
        self.response = requests.get(url=self.url)
        self.response2 = requests.get(url=self.url2)
        self.context = {
            "detailone": self.response.json(),
            "userss": self.response2.json()
        }
        return render(request, self.template_name, self.context)
    
    
class UpdateToDoView(generic.View):
    template_name = 'client/updatetodo.html'
    url_put = 'http://127.0.0.1:8000/api/todos/update/'
    url_get1 = 'http://127.0.0.1:8000/api/users'
    url_get2 = 'http://127.0.0.1:8000/api/todos'
    context = {}
    response = None
    def get(self, request, pk):
        self.url_get2 += f'/{pk}'
        self.response = requests.get(url=self.url_get1)
        print(self.url_get2)
        self.response2 = requests.get(url=self.url_get2)
        self.context = {
            "idusers":self.response.json(),
            "detail":self.response2.json()
        }
        return render(request, self.template_name, self.context)
    def post(self, request, pk):
        payload = {
            "title": request.POST.get("title"),
            "userid": int(request.POST.get("userid")),
            "status": request.POST.get("status"),
            "description": request.POST.get("description"),
            "due_date": request.POST.get("due_date"),
            "priority": request.POST.get("priority"),
            "created_at": datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3] + 'Z',
            "completed_at": None,
        }
        self.url_put += f'{pk}'
        self.response = requests.put(url=self.url_put, json=payload)
        return redirect("Client:index")
    
class DeleteToDoView(generic.View):
    url = 'http://127.0.0.1:8000/api/todos/delete/'
    response = None
    def get(self, request, pk):
        self.url += f'{pk}'
        self.response = requests.delete(url=self.url)
        return redirect("Client:index")
    
    
    
    
#################################################### USER  ####################################################
class RegisterView(generic.View):
    template_name = 'client/register.html'
    url_post = 'http://127.0.0.1:8000/api/users/new'
    context = {}
    
    def get(self, request):
        return render(request, self.template_name, self.context)
    
    @csrf_exempt
    def post(self, request):
        payload = {
            "username": request.POST.get("username"),
            "password": request.POST.get("password"),
            "rol": request.POST.get("rol"),
            "status": request.POST.get("status"),
        }
        self.response = requests.post(url=self.url_post, data=payload)
        return redirect("Client:index")
    
class LogoutView(generic.View):
    def get(self, request):
        request.session.flush()
        return redirect("Client:index")
    
  
 
    
    

Examen2/ToDoView/templates/client/createtodo.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Header Bootstrap</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>


{% block title %}MAKE A NEW TASK VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <div class="form-group">
              <label for="id_userid">UserID</label>
              <select name="userid" id="userid" class="form-control">
                {% for uid in idusers %}
                  <option value="{{ uid.id }}">{{ uid.username }}</option>
                {% endfor %}
              </select>
           </div>
            <button type="submit" class="btn btn-primary form-control">Create Task</button>
            <a href="{% url 'Client:index' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

Examen2/ToDoView/templates/client/detailtodo.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Header Bootstrap</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    {% block title %}DETAIL VIEW{% endblock title %}

    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Task Detail</h1>
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ detailone.title }}</h5>
                        <p class="card-text"><strong>ID:</strong> {{ detailone.id }}</p>
                        <p class="card-text"><strong>UserID:</strong> 
                        {% for u in userss %} 
                            {% if u.id == detailone.userid %}
                                {{ u.username }}
                            {% endif %}
                        {% endfor %}
                        </p>
                        <p class="card-text"><strong>Status:</strong> {{ detailone.status }}</p>
                        <p class="card-text"><strong>Description:</strong> {{ detailone.description }}</p>
                        <p class="card-text"><strong>Due Date:</strong> {{ detailone.due_date }}</p>
                        <p class="card-text"><strong>Priority:</strong> {{ detailone.priority }}</p>
                        <p class="card-text"><strong>Created:</strong> {{ detailone.created_at }}</p>
                        <p class="card-text"><strong>Completed:</strong> {{ detailone.completed_at }}</p>
                        <a href="/update/{{ detailone.id }}" class="btn btn-outline-warning">Update</a>
                        <a href="/delete/{{ detailone.id }}" class="btn btn-outline-danger">Delete</a>
                        <a href="{% url 'Client:index' %}" class="btn btn-outline-success">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock content %}
</body>
</html>

Examen2/ToDoView/templates/client/indexid.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Header Bootstrap</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    {% block content %}
    <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel">Login</h5>
                </div>
                <div class="modal-body">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <label for="username" class="form-label">Username</label>
                            <input type="username" class="form-control" id="username" name="username" placeholder="Enter your username" required>
                        </div>
                        <div class="form-group mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="text" class="form-control" id="password" name="password" placeholder="Enter your password" required>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Login</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <small>Don't have an account? <a href="/register">Register</a></small>
                </div>
            </div>
        </div>
    </div>
    

    {% if request.session.username %}
    <div class="container text-end mt-3">
        <a href="{% url 'Client:logout' %}" class="btn btn-danger">Logout</a>
    </div>
    {% endif %}

    <div class="container text-center">
        <h1 class="mt-3 mb-3">TASK "TO DO"</h1>
        <div style="overflow-y: scroll; height: 600px;">
            <div class="container mt-3">
                <div class="row mb-3">
                    <div class="col text-start">
                        <a href="/create" class="btn btn-primary">Create</a>
                    </div>
                    <div class="col text-end">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Filter
                            </button>
                            <ul class="dropdown-menu">
                                <li><hr class="dropdown-divider">General</li>
                                <li><a class="dropdown-item" href="/id_title">ID and Title</a></li>
                                <li><a class="dropdown-item" href="/id_userid">ID and UserID</a></li>
                                <li><hr class="dropdown-divider">Completed</li>
                                <li><a class="dropdown-item" href="/solved/id_title">ID and Title</a></li>
                                <li><a class="dropdown-item" href="/solved/id_userid">ID and UserID</a></li>
                                <li><hr class="dropdown-divider">Pending</li>
                                <li><a class="dropdown-item" href="/unsolved/id_title">ID and Title</a></li>
                                <li><a class="dropdown-item" href="/unsolved/id_userid">ID and UserID</a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <table class="table table-striped text-center">
                    <thead>
                        <tr>
                            <th colspan="4">ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        <div class="container text-center">
                            {% for i in ids %}
                                {% if forloop.counter0|divisibleby:4 %}
                                <tr>
                                {% endif %}
                                <td class="col-3">
                                    <a href="http://127.0.0.1:1234/detail/{{ i.id }}">
                                        <div class="col 
                                            {% if i.status == 'pending' %} bg-danger
                                            {% elif i.status == 'completed' %} bg-success 
                                            {% else %} bg-warning
                                            {% endif %} 
                                            text-white m-1 p-3">
                                            {{ i.id }}
                                        </div>
                                    </a>
                                </td>
                                {% if forloop.counter|divisibleby:4 or forloop.last %}
                                </tr>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var loginModal = new bootstrap.Modal(document.getElementById('loginModal'));
            {% if show_login_modal %}
                loginModal.show();
            {% endif %}
        });
    </script>

    {% endblock content %}
</body>
</html>

Examen2/ToDoView/templates/client/indexidtitle.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Order By ID and Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <div class="container mt-3 text-center">
        <h1>Order By ID and Title</h1>
        <table class="table table-striped text-center">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                </tr>
            </thead>
            <tbody>
                {% for i in idsandtitle %}
                <tr onclick="window.location.href='http://127.0.0.1:1234/detail/{{ i.id }}'" style="cursor: pointer;">
                    <td class="{% if i.status == 'pending' %} bg-danger {% elif i.status == 'completed' %} bg-success {% else %} bg-warning {% endif %} text-white m-1 p-3">{{ i.id }}</td>
                    <td class="{% if i.status == 'pending' %} bg-danger {% elif i.status == 'completed' %} bg-success {% else %} bg-warning {% endif %} text-white m-1 p-3">{{ i.title }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'Client:index' %}" class="btn btn-outline-warning" >Back</a>
    </div>
</body>
</html>

Examen2/ToDoView/templates/client/indexiduserid.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Order By ID and UserID</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <div class="container mt-3 text-center">
        <h1>Order By ID and UserID</h1>
        <table class="table table-striped text-center">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>UserID</th>
                </tr>
            </thead>
            <tbody>
                {% for i in idsanduserid %}
                <tr onclick="window.location.href='http://127.0.0.1:1234/detail/{{ i.id }}'" style="cursor: pointer;">
                    <td class="{% if i.status == 'pending' %} bg-danger {% elif i.status == 'completed' %} bg-success {% else %} bg-warning {% endif %} text-white m-1 p-3">{{ i.id }}</td>
                    <td class="{% if i.status == 'pending' %} bg-danger {% elif i.status == 'completed' %} bg-success {% else %} bg-warning {% endif %} text-white m-1 p-3">{{ i.userid }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'Client:index' %}" class="btn btn-outline-warning" >Back</a>
    </div>
</body>
</html>

Examen2/ToDoView/templates/client/register.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% block content %}
    <div class="container text-center mt-5">
        <div class="row justify-content-center align-items-center vh-50">
            <div class="col-md-6">
                <div class="card shadow-lg">
                    <div class="card-header">
                        <h3>Register</h3>
                    </div>
                    <div class="card-body">
                        <form method="post" action="/register">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input type="text" class="form-control" id="password" name="password" placeholder="Enter your password" required>
                            </div>
                            <div class="form-group mb-3">
                                <label for="bio" class="form-label">Bio</label>
                                <input type="text" class="form-control" id="bio" name="bio" placeholder="Enter your bio">
                            </div>
                            <div class="form-group mb-3">
                                <label for="rol" class="form-label">Role</label>
                                <select class="form-select" id="rol" name="rol">
                                    <option value="dev">Developer</option>
                                    <option value="viewer">Viewer</option>
                                    <option value="admin">Administrator</option>
                                </select>
                            </div>
                            <div class="form-group mb-3">
                                <label for="status" class="form-label">Status</label>
                                <select class="form-select" id="status" name="status">
                                    <option value="active">Active</option>
                                    <option value="inactive">Inactive</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Register</button>
                        </form>
                    </div>
                    <div class="card-footer text-center">
                        <small>Already have an account? <a href="/login">Login</a></small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock content %}

Examen2/ToDoView/templates/client/updatetodo.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Header Bootstrap</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

{% block title %}UPDATE TASK VIEW{% endblock title %}
{% block content %}
<div class="container mt-4">
    <h2>Update ToDo -> {{ detail.id}}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ detail.title }}" required>
        </div>
        <div class="form-group">
            <label for="userid">User</label>
            <select class="form-select form-control" id="userid" name="userid" required>
                {% for user in idusers %}
                    <option value="{{ user.id }}" {% if user.id == detail.userid %}selected{% endif %}>{{ user.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="status">Status</label>
            <select class="form-select form-control" id="status" name="status" required>
                <option value="pending" {% if detail.status == "pending" %}selected{% endif %}>Pending</option>
                <option value="completed" {% if detail.status == "completed" %}selected{% endif %}>Completed</option>
                <option value="in_progress" {% if detail.status == "in_progress" %}selected{% endif %}>In Progress</option>
            </select>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description" rows="4" required>{{ detail.description }}</textarea>
        </div>
        <div class="form-group">
            <label for="due_date">Due Date</label>
            <input type="datetime-local" class="form-control" id="due_date" name="due_date" value='{{ detail.due_date }}'>
        </div>
        <div class="form-group">
            <label for="priority">Priority</label>
            <select class="form-select form-control" id="priority" name="priority" required>
                <option value="low" {% if detail.priority == "low" %}selected{% endif %}>Low</option>
                <option value="medium" {% if detail.priority == "medium" %}selected{% endif %}>Medium</option>
                <option value="high" {% if detail.priority == "high" %}selected{% endif %}>High</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{% endblock content %}
</body>
</html>